### ISSUE TITLE
Remaining pieces for token generator

### ISSUE THREAD

**Issue by elaineo** [ethereumclassic/etherwallet#30]
- [x] [whitepaper generator](https://github.com/koinster/blockchain-whitepaper-generator)
- [x] ICO buy-tokens page
- [x] direct link to ICO
- [x] automatically load token details
- [x] gas estimations might be off - hardcode?
- [x] US dollar and BTC conversions on launch and buy pages
- [x] show user's current balance info
- [x] converter between ETC and tokens (X ETC will get you Y tokens)
- [x] Remove this nonsense from classicetherwallet.com

Let me know if I've missed anything.

**Comment by arvicco** [comment]
Poor ICO founders work too hard right now to get to their millions. We need to help them realize their dream of becoming crypto-millionaires without ever lifting their finger. Good luck in your noble endeavor!

**Comment by arvicco** [comment]
Another good starting point for whitepaper generator would be https://github.com/strib/scigen

**Comment by elaineo** [comment]
@arvicco hahaha, thanks! :D

**Comment by mikeyb** [comment]
My $0.02

I am assuming this feature is real and not a troll judging by there being actual work done on it.  However the content is incredibly childish throughout.

Some examples include:
*  `Scamcoin` placeholder for *Token Name*
*  `POOP` for the Token Symbol
*  The entire `What is the process like?` section could benefit from a complete overhaul of wording, including typos like `your` instead of `you're`.
*  The logo with a lambo and cash

This really doesnt help the crypto community in any way except to make it sound like all ICO's are scams and people are only in it for a quick buck.  My last conversation with most of you was regarding greed and how it was lusted for by some of the development team, from a token boasting honesty and change from the past.  This sort of product offering sheds a very negative light on ETC and crypto in general.

Hope to see some changes made to make this a bit more professional, if that is truly the crowd you are trying to attract.  Someone in another slack linked this to me and I had to triple check the url to make sure I was not on a scam site.

Cheers.

**Comment by elaineo** [comment]
@mikeyb It's a joke in response to this bug bounty: https://twitter.com/jgarzik/status/870066280426086400

**Comment by mikeyb** [comment]
okay whew!

**Comment by elaineo** [comment]
BTW, while I am not a fan of ICOs myself, if there is actual demand for such a service in the future it may be worthwhile to clean it up.

**Comment by elaineo** [comment]
This project has been moved to [TokenMint](https://github.com/ethereumproject/TokenMint)
